[package]
name = "trial"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-bert = "0.20.0"
ndarray = "0.15.4"
ollama-rs = "0.1.6"
tokio = { version = "1.0", features = ["full"] }
syn = { version = "2.0", features = ["full", "extra-traits", "visit"] }
rustpython-parser = "0.1.2"
quote = "1.0"